[package]
name = "macroquad_game_"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.14"
textwrap = "0.16.2"

[profile.release]
lto = true
opt-level = 'z'

[profile.dev.package.'*']
opt-level = 3